RootDirs:
  Database: /Users/rosiehoward/Documents/UBC/Micromet/FLUXNET-Canada-V2.0/Database
  Highfreq: C:/highfreq/
  EddyPro: C:/Program Files/LI-COR/EddyPro-7.0.9/bin/
  LocalOutputs: C:/temp/
  Datadump: X:/
